language: node_js
node_js:
  - stable

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run coverage
    - ./node_modules/.bin/codecov

sudo: false